### ISSUE TITLE
Incorrect test

### ISSUE THREAD

**Issue by dsatfire** [engintekin/javascript-coding-challenges-using-github-circleci#4]
The second test's array input does not match the "expected" input for the test.
The array [1,2,1,0,0,5,2,0,10,8,5] is does not produce the same result as [1,0,2,0,1,0,0,0,5,0,2,0,0,0,10,0,8,0,5] in the following test.

"it('returns 46 given array [1,0,2,0,1,0,0,0,5,0,2,0,0,0,10,0,8,0,5]', function () {
    expect(Solution.calculateAmountOfWaterCollected([1,2,1,0,0,5,2,0,10,8,5])).to.be.equal(46)
  });"

**Comment by engintekin** [comment]
thank you @dsatfire I've fixed it.

**Comment by engintekin** [comment]
@dsatfire as you are the first one who actually implemented a solution, what do you think repository?

**Comment by dsatfire** [comment]
I like it. You did a good job setting it up.
